# Generated by Django 3.2.2 on 2022-09-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
