# Generated by Django 3.2.2 on 2022-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Цена'),
        ),
    ]
